In [55]:
import numpy as np
import pandas as pd

In [56]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [57]:
print("キー:{}".format(cancer.keys()))
print("data形状:{}".format(cancer.data.shape))

キー:dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])
data形状:(569, 30)


In [60]:
cancer_data = cancer.data
cancer_data[:10]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [26]:

def count_target(cancer_target_names,cancer_target):
    A_name = cancer_target_names[0]
    count = []
    count[A_name] = []
    B_name = cancer_target_names[1]
    count[B_name] = []
    for counts in cancer_target:
        if counts == 0:
            count[A_name].append(counts)
        elif count == 1:
            count[B_name].append(counts)
    return count
    

In [27]:
cancer.target_names
cancer.target
# count 
A = count_target(cancer.target_names,cancer.target)

TypeError: list indices must be integers or slices, not numpy.str_

In [34]:
np.bincount?



array(['malignant', 'benign'], dtype='<U9')

In [35]:
names = ['Alice', 'Bob', 'Charlie']
ages = [24, 50, 18]

for name, age in zip(names, ages): # zipは二つの配列を対応ずける。
    print(name, age)

Alice 24
Bob 50
Charlie 18


In [36]:
for t,u in zip(cancer.target_names,np.bincount(cancer.target)):
    print("{0}:{1}".format(t,u))

malignant:212
benign:357


In [42]:
# なるほどdict型で表現する。
{t:u for t,u in zip(cancer.target_names,np.bincount(cancer.target))} # :いらない

{'malignant': 212, 'benign': 357}

In [48]:
print('特徴量:\n{}'.format(cancer.feature_names))

特徴量:
['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [49]:
print(cancer.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [50]:
from sklearn.model_selection import train_test_split

In [76]:
X_train,X_test,y_train,y_test =  train_test_split(cancer.data,cancer.target,random_state= 0)
# train,test,train,testと順番に気をつける。
#stratify はクラスバランス(比率)を考えて、データを分ける方法

In [73]:
# 指数表記変更のモジュールを入れる。
print(X_train,y_train)

[[1.185e+01 1.746e+01 7.554e+01 ... 9.140e-02 3.101e-01 7.007e-02]
 [1.122e+01 1.986e+01 7.194e+01 ... 2.022e-02 3.292e-01 6.522e-02]
 [2.013e+01 2.825e+01 1.312e+02 ... 1.628e-01 2.572e-01 6.637e-02]
 ...
 [9.436e+00 1.832e+01 5.982e+01 ... 5.052e-02 2.454e-01 8.136e-02]
 [9.720e+00 1.822e+01 6.073e+01 ... 0.000e+00 1.909e-01 6.559e-02]
 [1.151e+01 2.393e+01 7.452e+01 ... 9.653e-02 2.112e-01 8.732e-02]] [1 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 0 1 0 0 0 1 1 1 1 1 1 0 1 1 1 1 0
 0 1 1 0 1 1 1 1 0 1 1 0 0 1 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 1 1 0 1 0
 1 0 1 0 1 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 0 0 0 0 1 0 1
 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1
 0 1 0 0 1 0 0 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 0 1 0 1 1 1 1 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 1 1 0 0 1 1 0
 1 1 1 0 1 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 0 0 0 1 1 0 1 1
 1 0 0 1 1 1 1 1 0 0 0 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 0 1 0 

In [75]:
print(X_test,y_test)

[[1.340e+01 2.052e+01 8.864e+01 ... 2.051e-01 3.585e-01 1.109e-01]
 [1.321e+01 2.525e+01 8.410e+01 ... 6.005e-02 2.444e-01 6.788e-02]
 [1.402e+01 1.566e+01 8.959e+01 ... 8.216e-02 2.136e-01 6.710e-02]
 ...
 [1.234e+01 1.227e+01 7.894e+01 ... 1.070e-01 3.110e-01 7.592e-02]
 [1.353e+01 1.094e+01 8.791e+01 ... 7.407e-02 2.710e-01 7.191e-02]
 [1.959e+01 1.815e+01 1.307e+02 ... 2.247e-01 3.643e-01 9.223e-02]] [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 1 0 1 0
 0 1 1 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 0]


In [80]:
from sklearn import linear_model
clf1 =  linear_model.LinearRegression()
clf2 =  linear_model.LogisticRegression()

In [81]:
print(clf1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)


In [82]:
print(clf2)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)


In [83]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/Users/humu/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [84]:
print("clf1スコア:{}".format(clf1.score(X_test,y_test)))
print("clf2スコア:{}".format(clf2.score(X_test,y_test)))

clf1スコア:0.7291758706114044
clf2スコア:0.958041958041958


In [88]:
clf1.predict(X_test)

array([ 0.18812197,  0.81290682,  0.97218115,  0.80048339,  0.96034044,
        0.91645551,  1.0584662 ,  0.95753811,  1.06449265,  1.08269184,
        0.7341763 ,  0.77092697,  1.28729492,  0.71529399,  0.64098709,
        0.18411567,  1.04550353,  0.09998533,  0.08215325, -0.14623303,
       -0.01330402,  0.3365193 ,  0.83278001,  0.98588717,  0.23913363,
        0.94947383,  1.10085516,  0.35736277,  0.9358679 ,  0.02036455,
        1.02060302,  0.17575434,  0.67182846,  0.38867467,  1.28593693,
        0.08336373,  0.73895322,  0.32511537,  0.78658747, -0.00829554,
        0.41265285,  1.13713509,  0.4847475 ,  1.16140161,  0.60171498,
       -0.30244727,  1.36403947,  0.80801587,  0.99830909, -0.07567304,
        0.49061712,  0.65150854,  0.16661202,  0.92066123,  0.97574759,
        0.92761644,  1.04843363,  0.78957468,  0.8556918 ,  0.00360132,
        0.10459208,  0.16632026,  1.16419187,  0.89793586,  0.02595583,
        0.68885529, -0.5587198 , -0.31343995,  0.15255511,  1.01

In [86]:
clf2.predict(X_test)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0])

clf1では0,1の答えを0-1の値などで計算しているから正答率が悪くなる→logによって0or1にする。

In [98]:
print("clf1.coef_:\n {}".format(clf1.coef_)) # 係数
print("clf1.intercept_: \n{}".format(clf1.intercept_)) # 切片

clf1.coef_:
 [ 1.95664033e-01 -1.24998359e-02 -1.83925145e-02 -3.08554299e-04
 -6.58769659e-01  4.67316114e+00 -1.41047944e+00 -1.79519061e+00
 -1.02466251e+00 -8.16682870e-01 -6.95506836e-01 -2.65194673e-02
  6.52894932e-02  3.22253562e-04 -1.16323309e+01 -4.43943865e-02
  3.04134165e+00 -8.31729413e+00 -2.44644000e+00  1.96844051e+01
 -1.78964757e-01 -2.00410588e-04 -4.02896117e-03  1.17548563e-03
 -4.04988322e-01 -1.15267671e-01 -4.11583121e-01 -9.11239745e-01
 -1.12925131e-01 -5.02459596e+00]
clf1.intercept_: 
3.264323682949673


In [99]:
print("clf2.coef_:\n {}".format(clf2.coef_)) # 係数
print("clf2.intercept_:\n {}".format(clf2.intercept_)) # 切片

clf2.coef_:
 [[ 1.72216635  0.08980484  0.10598519 -0.00713449 -0.12840932 -0.33350116
  -0.4993638  -0.26508065 -0.26760721 -0.02149529  0.03647296  0.98655322
   0.11708827 -0.10871711 -0.00796626  0.01056064 -0.02918783 -0.02818291
  -0.0343139   0.00856785  1.35833542 -0.2890393  -0.24983343 -0.02012424
  -0.2169652  -1.02747458 -1.44796574 -0.5337783  -0.64856372 -0.10913524]]
clf2.intercept_:
 [0.35463393]
